export const FONTS: Array<[string, true?]> = [
  // web safe fonts
  ["'Arial', sans-serif", true],
  ["'Verdana', sans-serif", true],
  ["'Tahoma', sans-serif", true],
  ["'Trebuchet MS', sans-serif", true],
  ["'Helvetica', sans-serif", true],
  ["'Times New Roman', serif", true],
  ["'Georgia', serif", true],
  ["'Garamond', serif", true],
  ["'Palatino', serif", true],
  ["'Baskerville', serif", true],
  ["'Brush Script MT', cursive", true],
  ["'Comic Sans MS', cursive", true],
  ["'Bradley Hand', cursive", true],
  ["'Courier', monospace", true],
  ["'Lucida', monospace", true],
  ["'Monaco', monospace", true],
  // Google fonts
  ["'Roboto', sans-serif"],
  ["'Open Sans', sans-serif"],
  ["'Montserrat', sans-serif"],
  ["'Poppins', sans-serif"],
  ["'Lato', sans-serif"],
  ["'Roboto Slab', serif"],
  ["'Playfair Display', serif"],
  ["'Merriweather', serif"],
  ["'Lora', serif"],
  ["'Noto Serif', serif"],
  ["'Dancing Script', cursive"],
  ["'Pacifico', cursive"],
  ["'Lobster', cursive"],
  ["'Caveat', cursive"],
  ["'Satisfy', cursive"],
  ["'Roboto Mono', monospace"],
  ["'Source Code Pro', monospace"],
  ["'Space Mono', monospace"],
  ["'IBM Plex Mono', monospace"],
  ["'Ubuntu Mono', monospace"],
];
